package Construction;

public class Ecological extends Eco {

    //Calculates the amount of leftovers generated by the optimal subset's solution.
    protected long optimalValue(Project project, int mask) {
        long sizeSum = 0;
        for (int i = 0; i < project.getRequestLength(); i++) {
            if((mask & (1<<i)) != 0) {
                sizeSum += project.getRequest(i);
            }
        }

        return optimalRod(project, sizeSum).getSize() - sizeSum;
    }

    //Finds the most optimal solution based on the amount of leftovers (the smaller the better).
    protected StockRod optimalRod(Project project, long sizeSum) {
        StockRod currBest = new StockRod(Integer.MAX_VALUE, Integer.MAX_VALUE);

        for (int i = 0; i < project.getPricingLength(); i++) {
            StockRod currRod = project.getPricingRod(i);
            if (sizeSum <= currRod.getSize() && currRod.getSize() < currBest.getSize()) {
                currBest = currRod;
            }
        }

        return currBest;
    }

}
