[package]
name = "lab-07"
version = "0.2.0"
authors = ["Filip Plata <fp371335@students.mimuw.edu.pl>", "Mateusz Banaszek <m.banaszek@mimuw.edu.pl"]
edition = "2018"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
